version: '3'

services:
  
  vault:
    image: vaultwarden/server:1.28.1-alpine
    volumes:
    - "./vault/data:/data"
    env_file:
    - "./vault/env"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.vault.entrypoints=web"
    - "traefik.http.routers.vault.rule=Host(`vault.arpa`)"

  database:
    image: postgres:15.2
    volumes:
    - "./database/data:/var/lib/postgresql/data"
    env_file:
    - "./database/env"

  ingress:
    image: traefik:v2.10.0
    command:
    - "--log.level=INFO"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    - "--entrypoints.web.address=:80"
    ports:
    - "80:80"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"

